version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    image: flaskapp
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - UPLOAD_SECRET_KEY=${UPLOAD_SECRET_KEY}
  worker:
    image: flaskworker
    user: root
    build:
      context: ./worker
    depends_on:
      - redis
    environment:
      - UPLOAD_SECRET_KEY=${UPLOAD_SECRET_KEY}
  celery-flower:
    build:
      context: ./celery-flower
    command: celery flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - worker
      - redis